const characters = [
	{
		name: 'shelly',
		powerLevel: 2,
		powerPoints: 30,
		coins: 35,
		type: 'Rare',
		rank: 3,
		trophies: 22,
		image: '/img/shelly.jpeg',
	},
	{
		name: 'tara',
		powerLevel: 1,
		powerPoints: 20,
		coins: 20,
		type: 'Mythic',
		rank: 2,
		trophies: 10,
		image: '/img/tara.jpeg',
	},
	{
		name: 'Darryl',
		powerLevel: 7,
		powerPoints: 340,
		coins: 800,
		type: 'SuperRare',
		rank: 5,
		trophies: 44,
		image: '/img/darryl.jpeg',
	},
	{
		name: 'Nita',
		powerLevel: 3,
		powerPoints: 50,
		coins: 75,
		type: 'Rare',
		rank: 6,
		trophies: 61,
		image: '/img/nita.jpeg',
	},
	{
		name: 'ElPrimo',
		powerLevel: 7,
		powerPoints: 340,
		coins: 800,
		type: 'Rare',
		rank: 7,
		trophies: 61,
		image: '/img/ElPrimo.jpeg',
	},
];

export default characters;
